### ISSUE TITLE
Bezifferung der Punkte auf der Parameterseite von BO anpassen

### ISSUE THREAD

**Issue by wolfirr** [meschnigm/fhem#12]
![Bildschirmfoto von 2021-02-24 23-50-53](https://user-images.githubusercontent.com/59711600/109076626-2b48eb00-76fb-11eb-9b1a-f78c7414dd3a.png)
Hi Manuel,
die Zahlen gehen von 1 bis 6 und da ist die 6. BusinessOptimum und dann nochmal 6. Standardeinstellungen. Diese sollten unter 7. stehen.
Danke
Wolfgang

**Comment by meschnigm** [comment]
verbessert
