### ISSUE TITLE
Beschriftung auf der Wertetabellenseite anpassen

### ISSUE THREAD

**Issue by wolfirr** [meschnigm/fhem#13]
![Bildschirmfoto von 2021-02-24 23-51-51](https://user-images.githubusercontent.com/59711600/109076775-69dea580-76fb-11eb-9919-20d51c9900b6.png)
Es steht dort 'PPVundHH_Erzeugung' und muss 'PVundHH_Erzeugung' heißen.

Wobei ich sogar die Werte ganz anders benennen würde, nämlich:
- anstatt PVundHH_Verbrauch eher PVzuHH_Verbrauch, denn rein technisch ist der ursprüngliche Begriff nicht sinnvoll
- anstatt PVundHH_Erzeugung eher PV_Überschuss, denn der HH erzeugt doch nichts?

**Comment by meschnigm** [comment]
übernommen
