### ISSUE TITLE
cfg-Datei fuer den go-eCharger

### ISSUE THREAD

**Issue by ac-caterva** [meschnigm/fhem#14]
@meschnigm 
ich wuerde die Konfiguration fuer den go-eCharger gerne in eine separate Datei legen. Das fhem.cfg beruecksichtigt bisher nur die 00_Private.cfg. Koenntest du eine cfg Datei fuer den go-eCharger aufnehmen? Die Datei selber werde ich dann vom update ausschliessen, damit meine Konfiguration nicht ueberschrieben wird.

Ist das so wie ich das beschrieben habe moeglich?

**Comment by meschnigm** [comment]
mach einfach ein include go-eCharger.cfg in der 00_Private.cfg

 
Mit freundlichen Grüßen 
Manuel Meschnig

**Comment by ac-caterva** [comment]
Ok. Danke
