### ISSUE TITLE
FHEM inaktiv

### ISSUE THREAD

**Issue by Andycool29** [meschnigm/fhem#15]
Seit gestern 22:30 zeigt FHEM keine Daten mehr an. Habe FHEM neu gestartet, aber die anzeigen updaten sich nicht mehr. Die CS scheint zu funktionieren, zumindest höre ich den Schütz beim Laden/Entladen).
Manuel hast du noch eine Idee, was ich noch machen/testen sollte?
Danke vorab
<img width="1431" alt="Bildschirmfoto 2021-03-01 um 10 22 09" src="https://user-images.githubusercontent.com/76791588/109477707-a5b99800-7a78-11eb-896d-717922c4e79c.png">
<img width="1431" alt="Bildschirmfoto 2021-03-01 um 10 22 36" src="https://user-images.githubusercontent.com/76791588/109477731-af430000-7a78-11eb-9d22-67babdb49b8a.png">

**Comment by Andycool29** [comment]
Seit ca. 23:30, sorry. Ergänzung: Laut Log scheint die CS ja aktuell einzuspeichern

**Comment by ac-caterva** [comment]
wir koennen uns das heute abend ansehen. melde dich per PN im Discord.

**Comment by quinsifh** [comment]
Schaut bei mir auch so aus, ist wohl ein Problem Monatsende/Beginn. Wenn du nur auf einen Ausschnitt zoomst des heutigen Tages, geht das, zumindest bei mir...

**Comment by ac-caterva** [comment]
Problem Monatsende/Beginn im FHEM
@meschnigm 
Es war nicht das Problem mit dem copy_log.sh. Ich konnte bei Andycool29 ueberpruefn, dass das Script beim Monatswechsel funktioniert. Erscheint mir wie ein generelles FHEM Problem zu sein. Von mir aus kann das Issue geschloessen werden - ich habe keinen Button zum schliessen.
