### ISSUE TITLE
Begriffe 'Notladung' und 'Zwangsnachladung' in Grafik harmonisieren

### ISSUE THREAD

**Issue by wolfirr** [meschnigm/fhem#17]
Es steht oberhalb der Grafik 'Notladung' und unten in der Grafik 'Zwangsnachladung' mit roter Linie.
Fände es unmissverständlicher, wenn wir uns entweder für Notladung oder Zwangsnachladung einigen könnten :)
Danke!

**Comment by meschnigm** [comment]
Habs auf "Notladung" geändert kommt im nächsten Update
