### ISSUE TITLE
CS Gen1 - Zwangsnachladung

### ISSUE THREAD

**Issue by Andycool29** [meschnigm/fhem#18]
Habe gestern nacht bemerkt, dass die Zwangsnachladung ein paar mal angesprungen ist, obwohl SoC bei ca. 20% lag, Socmin =10%. Siehe auch Bildschirmfotos.
<img width="1431" alt="Bildschirmfoto 2021-03-08 um 08 02 10" src="https://user-images.githubusercontent.com/76791588/110286711-a8227180-7fe5-11eb-9e7b-57ea5a819a77.png">
<img width="1431" alt="Bildschirmfoto 2021-03-08 um 08 02 48" src="https://user-images.githubusercontent.com/76791588/110286737-b2447000-7fe5-11eb-9a69-97b4ca44cc43.png">
CS wird dann auf 25% geladen und kurz danach wiedeer entladen -> Wärmepumpe ist gerade aktiv. Das geht anscheinend so hin und her, sprich bei SoC 20% wird sie wieder auf 25% zwangsgeladen.

**Comment by meschnigm** [comment]
es scheint der Parameter SoCmin 20% verwendet zu werden. Möglicherweise wurden die Parameter nicht von der BO-Logik übernommen. Bitte einen beliebigen Parameter änderun --> absenden und in den **Lastloglines_BO** prüfen welche Parameter tatsächlich verwendet werden.

**Comment by Andycool29** [comment]
Das teste ich sobald meine CS wieder läuft. Aktuell ist die 24V-Versorgung defekt, warte auf Ersatzteil.

**Comment by ac-caterva** [comment]
@Andycool29 
besteht das Problem noch?
