### ISSUE TITLE
CS Gen1 - Entladung untere Schwelle

### ISSUE THREAD

**Issue by Andycool29** [meschnigm/fhem#19]
Die CS entlädt auch noch unter der eingestellten Schwelle von 1000 W, habe das Verhalten gestern abend erstmalig beobachtet, siehe beigefügten Graphen.

**Comment by Andycool29** [comment]
![Lesezeichen](https://user-images.githubusercontent.com/76791588/110288224-f89ace80-7fe7-11eb-9354-627817bf5875.png)
![Home, Sweet Home](https://user-images.githubusercontent.com/76791588/110288258-04869080-7fe8-11eb-8304-52ca48a3c4ae.png)
![Bildschirmfoto 2021-03-07 um 23 44 37](https://user-images.githubusercontent.com/76791588/110288299-110ae900-7fe8-11eb-8898-81f471a5f58e.png)

**Comment by meschnigm** [comment]
in diesem Fall bitte im Menü **lastloglines_BO** benutzen und Ergebnis hier posten.

**Comment by Andycool29** [comment]
Das teste ich sobald meine CS wieder läuft. Aktuell ist die 24V-Versorgung defekt, warte auf Ersatzteil.

**Comment by Andycool29** [comment]
24V-Versorgung passt wieder, allerdings läuft der Betrieb der CS nicht an. Folgende Fehlermeldungen kommen:
MacAlm(7) - Eigenverbrauchserhöhung wird nicht gezählt - Wartungsprozess anstoßen!
BusAlm(2) - Systemleistung maximal, Abweichungen möglich!

Hier die lastloglines_BO:
2021-03-29 10:56:09 || System noch nicht betriebsbereit (20/500) || [112:]
2021-03-29 10:56:19 || System noch nicht betriebsbereit (25/500) || [112:]
2021-03-29 10:56:26 || System noch nicht betriebsbereit (30/500) || [112:]
2021-03-29 10:56:32 || System noch nicht betriebsbereit (35/500) || [112:10]
2021-03-29 10:56:37 || System noch nicht betriebsbereit (40/500) || [112:12]
2021-03-29 10:56:43 || System noch nicht betriebsbereit (45/500) || [112:12]
2021-03-29 10:56:49 || System noch nicht betriebsbereit (50/500) || [112:12]
2021-03-29 10:56:55 || System noch nicht betriebsbereit (55/500) || [112:12]
2021-03-29 10:57:01 || System noch nicht betriebsbereit (60/500) || [112:12]
2021-03-29 10:57:06 || System noch nicht betriebsbereit (65/500) || [112:12]
2021-03-29 10:57:12 || System noch nicht betriebsbereit (70/500) || [112:12]
2021-03-29 10:57:18 || System noch nicht betriebsbereit (75/500) || [112:12]
2021-03-29 10:57:24 || System noch nicht betriebsbereit (80/500) || [112:12]
2021-03-29 10:57:30 || System noch nicht betriebsbereit (85/500) || [112:12]
2021-03-29 10:57:36 || System noch nicht betriebsbereit (90/500) || [112:12]
2021-03-29 10:57:42 || System noch nicht betriebsbereit (95/500) || [112:12]
2021-03-29 10:57:48 || System noch nicht betriebsbereit (100/500) || [112:12]
-> Systemzustandsabfrage     LLN0.Init.stVal... "112"
Systemaktivierungsabfrage    LLN0.Mod.ctlVal... "1"
-> Systemaktivierungsabfrage LLN0.Mod.ctlVal... "1"
Systembetriebsabfrage        LLN0.Mod.stVal.... "9"
-> Systembetriebsabfrage     LLN0.Mod.stVal.... "9"

System betriebsbereit und aktiviert

top - 10:58:03 up 3 min,  0 users,  load average: 4.78, 2.39, 0.96
 1065 root      20   0    3556   1388   1272 R  20.7  0.1   1:58.73 agetty
 1072 root      20   0    3376   1572   1456 S   0.0  0.2   0:00.02 agetty
  854 root      20   0    7192   4068    992 S   0.0  0.4   0:03.72 haveged
 4264 root      20   0    5356   3364   2188 S   0.0  0.3   0:00.57 monitor.sh

SoC 19 % < 30 % (Initialisierungsphase)
SoC 19 % ≤ 23 % bzw. Zell-Spannung zu niedrig 3480 mV ≤ 0 mV ?
--------------------------------------------------------------------------------------------------
System ist betriebsbereit, Nachladen wird gestartet - min. 10 min
----------------------------------------------------------------
29/03/2021 10:58:24 || Cell_Δ: 38 mV | SoC_Δ: 999 % | PVundHH: 107 W | Capa_% 999 % | SoC: 19 % | ChargedFlag: -1 | INV: 0 | INV: -0.00 W | Z | Nachladen
2021-03-29 10:58:29 || 60s warten, damit sich der Umrichter aktivieren kann bzw noch aktiviert
2021-03-29 10:59:30 || System - shutdown --- System war nicht aktivierbar
2021-03-29 10:59:50 || "shutdown -r now" nicht möglich, deswegen wird forcierter Reboot eingeleitet
====================================================================================================================================================
------------------------------------------------------------------------
Inhalt von nohup.out:
------------------------------------------------------------------------

BusinessOptimum: VA20_2021-01-24_18.00
2021-03-29 11:00:12 (NO WARRANTY)

Configuration of SN000002:
-------------------------------
P_in_W_chargeStandbyThreshold:          -1500 W
P_in_W_chargeStandbyThreshold_hyst:     -1000 W
P_in_W_dischargeStandbyThreshold:        2010 W
P_in_W_dischargeStandbyThreshold_delay:  1500 s
P_in_W_dischargeStandbyThreshold_hyst:   1000 s
SoC_max:                                 90 %
SoC_charge:                              80 %
SoC_discharge:                           30 %
SoC_min:                                 23 %
SoC_err:                                 0 %
counter_discharge_to_standby_max:        120 s
counter_standby_to_discharge_max:        60 s
counter_increment:                       4 s per loop without additional delay
loop_delay:                              -4 s (additional delay until rescan)
counter_increment_total:                 0 s (complete loop time, rescan every 0 s)
system_initialization:                   112
ECS3_configuration:                      PVHH
BusinessOptimum:                         1 (0: stand-alone // 1: BusinessOptimumStarter necessary)

loop_delay_int:                         0 ... 30 || aktuell: -4

Konfiguration war nicht ok, deswegen wird nun für einige Parameter eine Standardkonfiguration geladen

BusinessOptimum: VA20_2021-01-24_18.00
2021-03-29 11:00:13 (NO WARRANTY)

Configuration of SN000002:
-------------------------------
P_in_W_chargeStandbyThreshold:          -1500 W
P_in_W_chargeStandbyThreshold_hyst:     -1000 W
P_in_W_dischargeStandbyThreshold:        2010 W
P_in_W_dischargeStandbyThreshold_delay:  1500 s
P_in_W_dischargeStandbyThreshold_hyst:   1000 s
SoC_max:                                 90 %
SoC_charge:                              80 %
SoC_discharge:                           30 %
SoC_min:                                 23 %
SoC_err:                                 0 %
counter_discharge_to_standby_max:        120 s
counter_standby_to_discharge_max:        60 s
counter_increment:                       4 s per loop without additional delay
loop_delay:                              0 s (additional delay until rescan)
counter_increment_total:                 4 s (complete loop time, rescan every 4 s)
system_initialization:                   112
ECS3_configuration:                      PVHH
BusinessOptimum:                         1 (0: stand-alone // 1: BusinessOptimumStarter necessary)

System:                                  Gen1
BMMType:                                 Synerion48EGen3

**Comment by ac-caterva** [comment]
@Andycool29 
besteht das Problem noch

**Comment by quinsifh** [comment]
loop_delay_int: 0 ... 30 || aktuell: -4

Da wurde vom FHEM zur caterva -4 übertragen, damit falsche Konfiguration
