### ISSUE TITLE
Update - Fehler - Permission denied

### ISSUE THREAD

**Issue by quinsifh** [meschnigm/fhem#2]
2021.01.15 21:27:57 1 : FHEM::Meta::__GetUpdatedata: ERROR: Core file '   fhem.cfg' can only be updated from FHEM original update server
2021.01.15 21:27:58 2 : Backup with command: tar czf ./backup/FHEM-20210115_212758.tar.gz "./contrib" "./FHEM" "./demolog" "./log" "./fhem.pl" "./fhem.cfg.demo" "./restoreDir" "./docs" "./GPL_V2.txt" "./README.md" "./Bilder" "./www" "./configDB.pm" "./webserver" "./MAINTAINER.txt" "./unused" "./README_admin.md" "./lib" "./FHEM/00_Caterva_ESS.cfg" "./README_DEMO.txt" "./FHEM/00_BusinessOptimum_Parameter.cfg" "./FHEM/00_Private.cfg" "./fhem.cfg" "./CHANGED"
2021.01.15 21:28:00 1 : laeuft_BO 
2021.01.15 21:28:00 1 : PERL WARNING: Argument "" isn't numeric in numeric eq (==) at (eval 2300412) line 4.
2021.01.15 21:28:00 3 : eval: { my $laeuft_BO = `rsh admin\@caterva '/home/admin/bin/BusinessOptimumStarter.sh status_fhem'`; Log 1, "laeuft_BO $laeuft_BO"; if ($laeuft_BO == 1) { fhem("set BO_running 1"); } else { fhem("set BO_running 0"); } }
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300415) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300416) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300429) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300430) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300443) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300444) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300457) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300458) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300473) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300474) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300487) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300488) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300501) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300502) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300515) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300516) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300529) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300530) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300543) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300544) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300557) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300558) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300571) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300572) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300585) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300586) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300599) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300600) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300613) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300614) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300627) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300628) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300641) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300642) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300655) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300656) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300669) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300670) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300683) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300684) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300697) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300698) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300711) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300712) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300725) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300726) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300739) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300740) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300753) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300754) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300767) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300768) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300781) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300782) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300795) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300796) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300809) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300810) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300823) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300824) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300837) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300838) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300851) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300852) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300865) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300866) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300879) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300880) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300893) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300894) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300907) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300908) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300921) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300922) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300935) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300936) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300949) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300950) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300963) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300964) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300977) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300978) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2300991) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2300992) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301005) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301006) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301019) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301020) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301033) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301034) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301047) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301048) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301061) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301062) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301075) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301076) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301089) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301090) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301103) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301104) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301117) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301118) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301131) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301132) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301145) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301146) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 2301180) line 1.
2021.01.15 21:28:04 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaDay: Illegal division by zero at (eval 2301181) line 1.
2021.01.15 21:28:20 1 : backup tar: ./log/ESS_Minutenwerte-2021-01.log: Datei hat sich beim Lesen geändert.
2021.01.15 21:28:20 1 : backup done: FHEM-20210115_212758.tar.gz (54276872 Bytes)
2021.01.15 21:28:20 1 : 
2021.01.15 21:28:20 1 : fhem
2021.01.15 21:28:22 1 : nothing to do...
2021.01.15 21:28:22 1 : Downloading https://raw.githubusercontent.com/knowthelist/fhem-tablet-ui/master/controls_fhemtabletui.txt
2021.01.15 21:28:22 1 : 
2021.01.15 21:28:22 1 : fhemtabletui
2021.01.15 21:28:22 1 : nothing to do...
2021.01.15 21:28:22 1 : Downloading https://raw.githubusercontent.com/meschnigm/fhem/master/controls_webserver.txt
2021.01.15 21:28:22 1 : 
2021.01.15 21:28:22 1 : webserver
2021.01.15 21:28:22 1 : UPD Bilder/akku_uebersicht_1.png
2021.01.15 21:28:23 1 : open ./Bilder/akku_uebersicht_1.png failed: Permission denied, trying to restore the previous version and aborting the update

**Comment by meschnigm** [comment]
Das File ./Bilder/akku_uebersicht_1.png war fehlerhaft in die SW Verteilung gelangt. Skript ist angepasst.
