### ISSUE TITLE
ChargedFlag bleibt teilweise ungewollt gesetzt.

### ISSUE THREAD

**Issue by meschnigm** [meschnigm/fhem#21]
Das ChargedFlag bleibt teilweise ungewollt gesetzt - vielleicht wenn die Anlagen über die Sicherung ausgeschalten werden.
FHEM hat aktuell keine Möglichkeit das Problem zu beheben. Man müsste also ein Terminalfenster bemühen was nicht jeder 
kann...

Lösungsmöglichkeiten:

1) Abhilfe auf BO Seite: Flags in Ordner /tmp/ anlegen.
2) Als Abhilfe könnte ein Befehl `rm -f /home/admin/registry/noPVBuffering` per FHEM gesendet werden.
    Vorteil: einfach und unabhängig von der BO Version
    Nachteil: 
    - für Otto-Normalverbraucher schwer zu verstehen wann man auf diesen Knopf drücken soll.
    - Eingriff in die Logik von extern
                    
3) Alternativ vielleicht auch generell das Flag bei FHEM Neustart löschen... 
    Vorteil: keiner müsste sich kümmern 
    Nachteil: Eingriff in die Logik von extern

**Comment by ac-caterva** [comment]
Anmerkung von der Linux Fraktion:
Es ist generell besser Status und log-dateien im verzeichnis `/tmp` oder `/var/log` abzulegen. 
Erklärung:
`/tmp` ist ein in-memory Filesystem. Das bedeutet, daß die SDKarte keinen Verschleiß erleidet. Ausserdem ergibt sich dadurch, dass die Daten nach einem reboot nicht mehr vohanden sind. Somit besonders gut für Status Informationen geeignet, die den reboot nicht überleben sollen.
`/var/log` ist ein separates Filesystem, welches nur für log-dateien genutzt werden sollte. Unsere log-dateien dorthin zu speichern , könnte hoffentlich dazu führen, dass das root-filesystem, welches alle Programme und die Konfigurationsdateien enthält bei defekter SDKarte noch zu lesen ist.
