### ISSUE TITLE
FHEM oft/immer unerreichbar

### ISSUE THREAD

**Issue by schicho** [meschnigm/fhem#22]
Hallo ich bin der Basti, Sohn von SN94.

Ich kümmere mich bei uns um die Caterva (habe selbst keinen Zugang auf den Discord, sollte hier aber ebenfalls passend sein, das es sich offensichtlich um FHEM handelt).

Mein Problem ist seit dem Update auf webserver-public + Update von FHEM über das Menü in FHEM selbst, braucht FHEM ewig um mir die Weboberfläche zu zeigen.

Ursprünglich ging das sofort und das Login-Feld wurde sofort angezeigt. Nun warte ich mindestens 30 sek und länger bis das überhaupt geschieht. Seit gestern bekomme ich immer einen timeout bei der Verbindung. Irgendwas läuft da falsch auf Seiten von FHEM.

Um grundsätzliches schon mal aus dem Weg zu räumen:
- Ich kann die Caterva pingen ohne Problem, auch die Netzwerkverbindung auf Seiten der PI ist (über WLAN) gut genug
- Auf Port 80 served die Caterva sofort ohne lange Ladezeit die Standard Apache2 Website. Die Verbindung geht also sonst
- Ich habe FHEM als Service wie im ReadMe beschrieben schon neugestartet. Das war nicht erfolgreich
- Ebenfalls habe ich auch die PI neugestartet. Kein Erfolg - mindestens 30 Sekunden bevor das Login-Fenster kommt
- Selbst wenn ich mich dann einloggen kann, braucht FHEM manchmal ewig um mir eine neue Seite anzuzeigen (z.B. Wechsel von der Graphen- zur Tabellenansicht)

Was könnte das hier für ein Problem sein? Irgendeine Cache die ich vielleicht leeren muss oder ein Konfigurationsfehler nach dem Update? (Das Update habe ich vor ziemlich genau einen Monat gemacht).

LG,

Basti

**Comment by meschnigm** [comment]
Sorry ich habe die Nachricht nicht gesehen bis Anja mit darauf hingewiesen hat.

FHEM läuft auf dem Raspberry ich nehme an du meinst diesen Rechner wenn du von Caterva pingen sprichst.
Wir meinen mit Caterva den Business Controller mit der IP Endnummer 222. 
Die Apache2 Seite ist auf dem Raspberry - wenn hier die Verbindung klappt sollte es nicht an der grundsätzlichen erreichbarkeit liegen.

Du kannst mit putty auf den Raspberry zugreifen und das Logfile ansehen und idealerweise die Einträge nach einem Reboot prüfen evtl hier einstellen.

/opt/fhem/log/fhem-2021-06. log (oder so ähnlich)
unter 
/opt/fhem/log/ESS_Minutenwerte.... sollten sich die aktuellen Rohdaten finden die FHEM anzeigen soll.

**Comment by schicho** [comment]
Hallo Manuel,

danke für die Antwort. Inzwischen scheint sich das Problem von selbst behoben zu haben. FHEM ist auf dem Raspy ist inzwischen wieder ohner Probleme erreichbar und läuft wie gewöhnlich.
Ich weiß nicht was da das Problem war.

LG,

Basti
