### ISSUE TITLE
keine Anzeige der Daten in 2_Wertetabellen

### ISSUE THREAD

**Issue by ac-caterva** [meschnigm/fhem#3]
@meschnigm 
Seit dem letzten update, werden keine Werte in der Anzeige 2_Wertetabellen angezeigt.

`update check`
``` 
Downloading https://fhem.de/fhemupdate/controls_fhem.txt

fhem
nothing to do...
Downloading https://raw.githubusercontent.com/knowthelist/fhem-tablet-ui/master/controls_fhemtabletui.txt

fhemtabletui
nothing to do...
Downloading https://raw.githubusercontent.com/meschnigm/fhem/master/controls_webserver.txt

webserver
List of new / modified files since last update:
UPD FHEM/00_Private.cfg (excluded from update)

New entries in the CHANGED file:
2021-01-09 initial Version with FHEM SW distribution
2021-01-09 README update - Übertrag Bilder
2021-01-13 BO on/off hidden
2021-01-14 No auto backup | No readback for system_initialization and BusinessOptimum_BOS
2021-01-16 Menüeintrag für Logfile BusinessOptimum anzeigen / BO auf Port 83 
2021-01-16 exclude from update of 00_Private.cfg
2021-01-16 BusinessOptimum Befehle Stop Modul_Balancing Cell_Balancing
```
![grafik](https://user-images.githubusercontent.com/59482410/104851879-eeb5f280-58f7-11eb-8668-ad4039e1f39d.png)

`restart fhem` habe ich schon probiert. Hast du noch eine Idee?

**Comment by meschnigm** [comment]
prüfe mal diese Ansicht...
![grafik](https://user-images.githubusercontent.com/46651977/104854677-67bd4600-5908-11eb-926a-d74206cb203c.png)

Das erste Datum muss aktualisiert werden sobald die Datein /opt/fhem/log/ESS_Minutenwerte.... geschrieben wird.
Wenn dort kein aktuelles Datum steht also den Timestamp des Files prüfen.
Das geht am einfachsten mit 
{`ls -l /opt/fhem/log/ESS_Minutenwerte*`} 
in der FHEM EIngabezeile.
(Achtung vor und nach der geschwungenen Klammer ist ein Backtick- diesen sieht man nur im editmodus)


Wenn dies nicht aktuell ist das 
./var/caterva/scripts/copy_log.sh
im Terminal ausführen und eventuelle Fehlermeldungen prüfen.

Sollte das ESS_Minutenwerte keinen aktuellen Timestamp haben sind diese Einstellungen zu prüfen ob hier versehentlich etwas geändert wurde.
![grafik](https://user-images.githubusercontent.com/46651977/104854934-d51da680-5909-11eb-8b35-976881174ed6.png)

![grafik](https://user-images.githubusercontent.com/46651977/104854976-2cbc1200-590a-11eb-9c85-30f37628d393.png)

Wichtig ist auch der Code bei CMD1
{
createReadings_ESS_Minutenwerte("$SELF");
}

**Comment by ac-caterva** [comment]
ich hab nachgesehen und einen kleinen Film gemacht. Hoffe du kannst erkennen wo das Problem liegt.

https://user-images.githubusercontent.com/59482410/104891142-d0400d80-5970-11eb-8e0e-7b78b4969941.mp4

**Comment by ac-caterva** [comment]
ich habe es geschafft die beiden CMD wieder einzutragen und schwups geht es wieder. 
DANKE
