### ISSUE TITLE
Inverterleistung (PIsoll not PIset), 5555.0!=1112.657958984375

### ISSUE THREAD

**Issue by ulabein** [meschnigm/fhem#4]
Für den Graphen Einspeichern habe ich dir den wert 57 aus dem ESS minutenfile gegeben:
```
_57_=$(echo ${_INVOICELOGAKTUELL_} | cut -d ";" -f6 | cut -d "." -f1)                           # Recharge by power purchase in W
```
Das ist aber der Sollwert der eigentliche Wert was der Inverter liefert ist dieser
```
_25_=$(echo ${_INVOICELOGAKTUELL_} | cut -d ";" -f18 | cut -d "." -f1)                          # Pos. Inverter AC power in W
```
Das Problem tritt nur auf wenn dieser Fehler angezeigt wird.
```
06/01/2021 10:57:13.239  ERROR  [Alarm] SoftAssetProtectionBeanInstance renewed BusAlm(01) Underperformance "requested power differs from executed power (PIsoll not PIset), 5555.0!=1116.300048828125"
```

Aber prinzipiell sollte es so sein das in allen Graphen statt _57_ der _25_ für das laden verwendet wird,
und für das entladen _59_ der _23_ Parameter aus dem /opt/fhem/log/ESS_Minutenwerte-${_DATUM_}.log.

Das hätte den Vorteil das man sieht was der Inverter macht und nicht nur was wer vorgegeben bekommt.

**Comment by meschnigm** [comment]
Impementiert am 23.01.

**Comment by ulabein** [comment]
Hallo Manuel,

leider habe ich durch die Änderung ein Problem entstanden.
Kann das Ticket leider nicht mehr öffnen denke habe zu wenig Rechte.
![Bildschirmfoto vom 2021-01-30 15-55-00](https://user-images.githubusercontent.com/60625731/106359513-97f6e280-6313-11eb-8a51-5b2575248566.png)
Bei der Zwangsnachladung ist jetzt auch 25 drinnen, damit wird beim normalen laden 
auch immer Zwangsnachladung angezeigt.
Denke der muss auf 57 bleiben. 

Gruß uli
PS: Je länger ich drüber nachdenke bin ich mir nicht mehr sicher,
weil das ja eigentlich das Diagramm das ich anders haben wollte... ich muss nochmal nachdenken

**Comment by ulabein** [comment]
Man müsste bei Zwangsnachladung 2 Parameter anschauen,
was der Inverter lädt 57 und was die SW anforderter was geladen werden soll 25.
Da diese Differenz ja das eigentliche Issue Thema ist.
Da habe ich beim erstellen zu wenig drüber nachgedacht :-(

**Comment by meschnigm** [comment]
Bitte update testen...

 
Mit freundlichen Grüßen 
Manuel Meschnig

**Comment by ulabein** [comment]
Danke jetzt ist wieder Originalstand.
Habe jetzt bei mir nochmal versucht das darzustellen, Türkis 1100 Watt rot was er laden soll 5555 Watt.
Aber leider kann man das nicht so machen weil sonst beim Einspeichern, das türkise und das gelbe übereinander sind und
grün werden.
![Bildschirmfoto vom 2021-01-30 19-39-12](https://user-images.githubusercontent.com/60625731/106365060-57a75c80-6333-11eb-8587-7ce820884330.png)
![Bildschirmfoto vom 2021-01-30 19-44-13](https://user-images.githubusercontent.com/60625731/106365105-93422680-6333-11eb-9844-eebb9eabb86e.png)
Schwierig darzustellen.
Vielleicht das die Einspeicherung immer den Inverterladung bekommt 25 und die Notladung 57.
Wenn du es verständlich findest bau es so ein ansonsten lasse es einfach so.
![Bildschirmfoto vom 2021-01-30 19-49-56](https://user-images.githubusercontent.com/60625731/106365251-883bc600-6334-11eb-957b-edbff7da5583.png)
