### ISSUE TITLE
Bedingungen für CellBalancing und Modul-Balancing

### ISSUE THREAD

**Issue by quinsifh** [meschnigm/fhem#5]
**Cell-Balancing**
/home/admin/registry/out/bmmType:     Inhalt: "sony"   oder  Synerion48EGen3_ESSG2"

**Modul-Balancing**
1. /home/admin/registry/out/gen2        muss existieren und 
2. /home/admin/registry/out/bmmType    Inhalt:  "sony"

Wenn die Bedigngunen erfüllt könnten die Funktionen zum Einschalten Cell-Balancing und Modul-Balancing erst dann sichtbar werden. Dito wenn es um die Anzeige Aktiv geht.

**Comment by wolfirr** [comment]
@quinsifh auch wenn es hier womöglich falsch gelegen ist, aber sind die Bedingungen für das Cell-Balancing bei der Synerion (SAFT) Anlage die gleichen wie bei den Sony Anlagen?
Meine Saft Anlage läuft nämlich ständig mit BO ins Cell-Balancing, wenn die Differenz ca 35mV ist.
