### ISSUE TITLE
Illegal division by zero at (eval 538428) line ....

### ISSUE THREAD

**Issue by quinsifh** [meschnigm/fhem#6]
Bei mir kommen leider immer noch diese Fehlermeldungen:

> 2021.01.24 09:29:09 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 546198) line 1.
> 2021.01.24 09:29:09 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 546212) line 1.
> 2021.01.24 09:29:09 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 546226) line 1.
> 2021.01.24 09:29:09 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 546240) line 1.
> 2021.01.24 09:29:09 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 546254) line 1.
> 2021.01.24 09:29:09 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 546268) line 1.
> 2021.01.24 09:29:09 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 546282) line 1.
> 2021.01.24 09:29:09 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 546296) line 1.
> 2021.01.24 09:29:09 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 546310) line 1.
> 2021.01.24 09:29:09 1 : Error evaluating ESS_Minutenwerte userReading prozUeber_CatervaMonth: Illegal division by zero at (eval 546324) line 1

**Comment by meschnigm** [comment]
Bitte FHEM release vom 14.02. testen

**Comment by quinsifh** [comment]
Problem mit neuer Version nicht mehr vorhanden, ich hab das nun einige Tage laufen lassen
