### ISSUE TITLE
FHEM zeigt falschen Status von BO an

### ISSUE THREAD

**Issue by wolfirr** [meschnigm/fhem#7]
Weiß jetzt nicht, ob es hier richtig ist, aber schaut mal folgende Ausdrucke an. Nachdem FHEM auf den aktuellen Stand gebracht habe, es auch öfter neu gestartet habe, wir leider nicht angezeigt, dass BO noch mit Zellbalancing läuft und überhaupt läuft?
![Bildschirmfoto von 2021-01-29 20-22-23](https://user-images.githubusercontent.com/59711600/106335645-879c2480-628d-11eb-8a4d-f651cba3a756.png)
![Bildschirmfoto von 2021-01-29 20-23-29](https://user-images.githubusercontent.com/59711600/106335653-8a971500-628d-11eb-8afd-d57f2ed1c0a9.png)
![Bildschirmfoto von 2021-01-29 23-57-52](https://user-images.githubusercontent.com/59711600/106335876-f5485080-628d-11eb-8f63-27e9ee5b40a9.png)

**Comment by meschnigm** [comment]
bitte in der aktuellen Version testen.

**Comment by wolfirr** [comment]
hab Update durchgeführt, geht trotzdem nicht, da passt was mit den Verzeichnissen vielleicht nicht?
Folgenden Screenshot hab ich aufgenommen, da ist auch eine Diskrepanz zwischen ausgeführtem FHEM_Setup_Copy_per_Shell.sh und das FHEM es als noch nicht ausgeführt erkennt, aber nochmaliges Ausführen die Ausgabe bringt, es wurde schon ausgeführt. Die ganzen Abfragen nach dem Status von BO auf der CS scheinen nicht richtig erkannt zu werden:
![Bildschirmfoto von 2021-02-03 00-00-47](https://user-images.githubusercontent.com/59711600/106674510-a2370c00-65b3-11eb-8900-a508a846a919.png)
Unter dem Terminalfenster ist der FHEM Log zu sehen, wo nicht erkannt wird, das BO installiert und aktiv ist. Funktioniert der Zugriff auf die CS nicht mehr? Kann das sein, wegen 'Host key verification failed':

```
2021.02.02 23:50:03 3: set ECS3_configuration  : no set value specified
2021.02.02 23:50:03 1: PERL WARNING: Use of uninitialized value $config_array[16] in numeric eq (==) at ./FHEM/99_myUtils.pm line 58.
2021.02.02 23:50:03 3: eval: my $EVENT=   $evalSpecials->{'%EVENT'};my $EVTPART0=   $evalSpecials->{'%EVTPART0'};my $NAME=   $evalSpecials->{'%NAME'};my $SELF=   $evalSpecials->{'%SELF'};my $TYPE=   $evalSpecials->{'%TYPE'};{readfromcaterva_BusinessOptimum_config();read_PV_Peak();read_BO_Version();if(check_File_exists_PI('/home/pi/Git-Clones/.FHEM_Setup_Copy_per_Shell.did_run') == "1") {Log 1,"Skript FHEM_Setup_Copy_per_Shell auf dieser Anlage bereits gelaufen -> Rechte sind eingestellt"} else {"bla bla"}}
2021.02.02 23:50:03 1: PERL WARNING: Use of uninitialized value $config_array[16] in numeric eq (==) at ./FHEM/99_myUtils.pm line 62.
2021.02.02 23:50:03 3: eval: my $EVENT=   $evalSpecials->{'%EVENT'};my $EVTPART0=   $evalSpecials->{'%EVTPART0'};my $NAME=   $evalSpecials->{'%NAME'};my $SELF=   $evalSpecials->{'%SELF'};my $TYPE=   $evalSpecials->{'%TYPE'};{readfromcaterva_BusinessOptimum_config();read_PV_Peak();read_BO_Version();if(check_File_exists_PI('/home/pi/Git-Clones/.FHEM_Setup_Copy_per_Shell.did_run') == "1") {Log 1,"Skript FHEM_Setup_Copy_per_Shell auf dieser Anlage bereits gelaufen -> Rechte sind eingestellt"} else {"bla bla"}}
Host key verification failed.
2021.02.02 23:50:04 3: setreading ESS_Minutenwerte 09_PVpeak_in_W_2  : Usage: setreading <name> [YYYY-MM-DD HH:MM:SS] <reading> <value>
where <name> is a single device name, a list separated by comma (,) or a regexp. See the devspec section in the commandref.html for details.

Host key verification failed.
2021.02.02 23:50:04 1: PERL WARNING: substr outside of string at ./FHEM/99_myUtils.pm line 1010.
2021.02.02 23:50:04 3: eval: my $EVENT=   $evalSpecials->{'%EVENT'};my $EVTPART0=   $evalSpecials->{'%EVTPART0'};my $NAME=   $evalSpecials->{'%NAME'};my $SELF=   $evalSpecials->{'%SELF'};my $TYPE=   $evalSpecials->{'%TYPE'};{readfromcaterva_BusinessOptimum_config();read_PV_Peak();read_BO_Version();if(check_File_exists_PI('/home/pi/Git-Clones/.FHEM_Setup_Copy_per_Shell.did_run') == "1") {Log 1,"Skript FHEM_Setup_Copy_per_Shell auf dieser Anlage bereits gelaufen -> Rechte sind eingestellt"} else {"bla bla"}}
2021.02.02 23:50:04 1: PERL WARNING: Use of uninitialized value $Version in numeric gt (>) at ./FHEM/99_myUtils.pm line 1011.
2021.02.02 23:50:04 3: eval: my $EVENT=   $evalSpecials->{'%EVENT'};my $EVTPART0=   $evalSpecials->{'%EVTPART0'};my $NAME=   $evalSpecials->{'%NAME'};my $SELF=   $evalSpecials->{'%SELF'};my $TYPE=   $evalSpecials->{'%TYPE'};{readfromcaterva_BusinessOptimum_config();read_PV_Peak();read_BO_Version();if(check_File_exists_PI('/home/pi/Git-Clones/.FHEM_Setup_Copy_per_Shell.did_run') == "1") {Log 1,"Skript FHEM_Setup_Copy_per_Shell auf dieser Anlage bereits gelaufen -> Rechte sind eingestellt"} else {"bla bla"}}
2021.02.02 23:50:05 1: response: 255

2021.02.02 23:50:05 1: /home/admin/bin/BusinessOptimum.sh does not exist
2021.02.02 23:50:05 1: response: 255
```

**Comment by ac-caterva** [comment]
@wolfirr 
bei mir funktioniert es, lastloglines im FHEM:
```
2021.02.04 10:51:49 1: response: 0

2021.02.04 10:49:49 1: /home/admin/bin/BusinessOptimum.sh exists
2021.02.04 10:49:51 1: response: 0

2021.02.04 10:49:51 1: /tmp/BusinessOptimumActive exists
2021.02.04 10:49:53 1: response: 2

2021.02.04 10:49:53 1: /tmp/ForcedChargingActive does not exist
2021.02.04 10:49:56 1: response: 2

2021.02.04 10:49:56 1: /tmp/ModuleBalancingActive does not exist
2021.02.04 10:49:58 1: response: 2

2021.02.04 10:49:58 1: /tmp/CellBalancingActive does not exist
```

Bitte melde dich im Discord mit einem Terminvorschlag, dann sehe ich mir das auf deiner Anlage an.

LG, Anja

**Comment by meschnigm** [comment]
BuinessOptimum muss erst installiert werden. Das ist derzeit ja weder in der Verteilung von FHEM dabei noch wird es automatisch durch Anjas SW Verteilung verteilt und konfiguriert.

Also nach SW Update (Anja) die Files zur Caterva kopieren ...
```
scp /home/pi/Git-Clones/webserver-public/caterva/BusinessOptimum/VA2/BusinessOptimum.sh admin@caterva:/home/admin/bin
scp /home/pi/Git-Clones/webserver-public/caterva/BusinessOptimum/VA2/BusinessOptimum.config admin@caterva:/home/admin/bin
scp /home/pi/Git-Clones/webserver-public/caterva/BusinessOptimum/BusinessOptimumStarter.sh admin@caterva:/home/admin/bin
```

danach prüfen ob der Crontab Eintrag zum automatischen Start vorhanden ist...
`crontab -e`

hier sollte folgender Eintrag zu finden sein
```
# BusinessOptimumStarter nach reboot starten
@reboot /home/admin/bin/BusinessOptimumStarter.sh start
```
dann Caterva über FHEM mit `restart caterva` neu starten
Danach sollte die installierte Version in grün angezeigt werden


Besser wäre natürlich ein Skript zur Verteilung.....

**Comment by wolfirr** [comment]
Die fehlerhafte Anzeige lag wohl an nicht vorhandenen Zugriffsrechten des Users FHEM von der Pi auf den BC. Ist jetzt behoben.
