### ISSUE TITLE
Auslesen der CS Daten nach Monatswechsel nicht mehr möglich

### ISSUE THREAD

**Issue by wolfirr** [meschnigm/fhem#8]
Trotz updates von FHEM werden nur Werte bis 31.1.2021 23.58h angezeigt.
Hab das Problem nur ich?

**Comment by quinsifh** [comment]
Habe ich auch, das copy_log.sh sollte die Rechte umstellen, da das file jedoch nicht pi gehört, geht das nicht.
Da muss wohl eher eine Änderung erfolgen durch @ac-caterva damit das zukünftig wieder richtig läuft.
workaround:
sudo chmod 664 /opt/fhem/log/ESS_Minutenwerte-2021-02.log

Dann funktioniert das wieder.....

**Comment by wolfirr** [comment]
Danke @quinsifh für den Workaround, funktioniert zunächst!

**Comment by ulabein** [comment]
FHEM is unschuldigt,
denke reicht wenn wir das da tracken. 
https://github.com/ac-caterva/Technik/issues/69

**Comment by ac-caterva** [comment]
ja, bitte weiter [ac-caterva/Technik#69](https://github.com/ac-caterva/Technik/issues/69) beobachten.
