### ISSUE TITLE
sub1.html - Parameter von 25 auf 75 ändern (Nachladen)

### ISSUE THREAD

**Issue by quinsifh** [meschnigm/fhem#9]
![image](https://user-images.githubusercontent.com/61943913/107123158-406cef80-689c-11eb-86e9-37e0e4fffab2.png)

das muss hier noch angepasst werden.

**Comment by meschnigm** [comment]
implemented with Version 2021-02-07 
Bugfix BO_Version auslesen - Issue #9 sub1.html - Parameter von 25 auf 75 ändern (Nachladen)
